### ISSUE TITLE
Locking slots acts weird with Tweakeroo hotbar swapping

### ISSUE THREAD

**Issue by iainvm** [Origins-Tech/InventiveInventory#3] opened 2024-08-27 18:41 UTC
I use Tweakeroo to swap my hotbar with one of my other inventory rows
I was using version `0.4.6` of your mod to lock one of my inventory rows to not sort
This basically means one of my inventory rows is like a 2nd hotbar I can swap in and out quickly

However, since updating to version `1.0.1` of your mod, things go a bit weird when Tweakeroo swaps the rows back into my inventory

Setup:
- Have Inventive Inventory & Tweakeroo installed
- Enable Tweakeroo's "HotbarScroll" tweak
- Lock the bottom row in your inventory
- Put something stackable in your hotbar like torches or rockets
- Use the "Hotbar Scroll" to swap your hotbar with the bottom locked row of your inventory

## What Happens
1 of the torches will be correctly placed in the locked row
However, 63 will be placed in a different inventory slot

## What should happen
All 64 items should be in the slot on the locked row

**Comment by iainvm** [comment] 2024-08-27 19:19
I believe it to be part of this feature
```
Additionally, picked-up items won't be placed in such a slot either and will rather get dropped.
(In singleplayer this works even with quick-moving items, on servers quick-move preventing is currently not available)
```

But there doesn't seem to be a way to toggle this at all

**Comment by Strobel273** [comment] 2024-08-27 21:38
Hey,
thanks for your report.
We will investigate this problem soon.

Your Inventive Inventory Team

**Comment by Strobel273** [comment] 2024-08-28 17:18
May I ask why you use Tweakeroo and Inventive Inventory? What offers our mod for you what Tweakeroo doesn't have? (Just out of interest)

**Comment by Strobel273** [comment] 2024-08-29 12:01
Hey iainvm,
we think we've found a solution and fixed it.
Altough, we would prefer if you first try it out, just to go sure it fits your need and no other bugs occur with your configuration or mods.

As i can't append the jar file to this message, maybe i could send it to you via Discord? (disturbtion <- You can just contact me)

We hope it works for you and look forward to your feedback.

Greetings,
Your Inventive Inventory Team

**Comment by iainvm** [comment] 2024-08-29 16:55
Hey I've cloned and compiled it locally
Loads fine and the hotbar swaps as expected

Though putting a single rocket in the locked inventory slot, then dropping 63 of them on the ground fill the locked slot. Doesn't this go against what is quoted in the above feature?

**Comment by iainvm** [comment] 2024-08-29 17:40
Also when shift clicking items from a chest, I can see it being placed in a non-locked slot, but then immediately move to a locked slot

**Comment by Strobel273** [comment] 2024-08-29 17:44
Actually, I can't reproduce the first behaviour.
If your Inventory is open at the moment of pick-up then this functionality is disabled because it is very tricky if not impossible to not compute this while a player does or drag items and stuff. So it should work if you try to pick-up with closed inventory. 
Do you test in singleplayer on in multiplayer?

As for the chest thing, yeah i should look into this. There's something wrong now.

**Comment by iainvm** [comment] 2024-08-29 18:14
Ahh, it was while my inventory was open so that's why I saw that behaviour
I was testing in multiplayer

**Comment by Strobel273** [comment] 2024-08-30 17:42
We have a quick update for you.
We achived to make the pick-up functionality also work with opened inventory.

The problem with the chest still persists, but tbf it wasn't in the mod beforehand actually :) 
We will still try to include this feature as it is on our TODO list anyway.

I will get in touch with you again as soon as this problem is solved as well.

Greetings

**Comment by iainvm** [comment] 2024-09-01 15:57
Can I ask if there will be a settings switch for the feature of locked slots don't pick up items. Since that would work for me since I don't need that feature

**Comment by Strobel273** [comment] 2024-09-02 09:01
Yeah, of course. We've uploaded it to the repo.
You can just clone and build yourself. We'll try to release the new public version soon.

I'll close this issue now. If any other problems occur, please let us know.

Best regards

**Closed by Strobel273** 2024-09-02 09:01 UTC
Labels: bug

**Comment by iainvm** [comment] 2024-09-03 17:44
Thanks, will open any issues I find, initial testing seems fine with "Pick-Up into Locked Slots" set to "Yes"

**Comment by Disturbtion273** [comment] 2024-09-16 13:32
Hey there,
we have enrolled a new version of our mod. It comes directly with support for the Tweakeroo mod and you can now download it easily again via Modrinth or Curseforge with the convenience of getting updates and everything these launchers have to offer.
So just remove the jar file from your mods folder and install it from your launcher.

Thanks for using our mod
Your Inventive Inventory Team
